### PR TITLE
Changing / Optimizing / Adding options

### PR DESCRIPTION
**Pull request by kaldoran**
I did rework a bit the code with divers optimization.
I also modify some part of code in order to add the possibility to choose the color. 

Finally, I did create an emulation on wokwi : https://wokwi.com/projects/348695052670730836

### CODE REVIEW

**Comment by designer2k2** [comment]
Hello, thanks for the PR!
The simulation is impressive :-)

First thing in the code ive seen you increased the brightness from 40 to 255, did you check the current draw?

**Comment by kaldoran** [comment]
I did not sorry :x 
I did change it from 40 to 255 just in order to have a correct simulation on wokwi.
I change the code right now, it should update the PR

**Comment by kaldoran** [comment]
For information, I did try to add a new effect, which you can see here : 
https://wokwi.com/projects/348700019704988244

It's the tree function, but the "candles' are random.

```
void treeRandom(uint32_t _color) {
  uint8_t ringSize, led, totalLed = TOTAL_LED;
  colorWipe(_color, 50); // Green

  //light "candles"
  //Show the S:
  for (ringSize = 0;ringSize < SIZEOFARRAY(ringsSize); ++ringSize) {
    for(led = 0; led < ringsSize[ringSize] / 3; led++) {
      strip.setPixelColor(random(totalLed - ringsSize[ringSize], totalLed), strip.Color(255, 255, 255));
      strip.show();
      delay(50);
    }

    totalLed -= ringsSize[ringSize]; 
  }
}
```
The '3' in the code is randomly choose [I want at most "ringSize / 3' candle per circle].

PS : Thank you for your amazing job and sharing :+1:

**Comment by designer2k2** [comment]
i will try it my tree here over the weekend

**Comment by kaldoran** [comment]
I did update a bit the function : 
```
//This lights up the tree in _color, then add the white random "candles" 
void treeRandom(uint32_t _color, bool _blink) {
  uint8_t ringSize, led, totalLed = TOTAL_LED;
  
  if (_blink) { strip.fill(_color); strip.show(); }
  else colorWipe(_color, 50);
  delay(400);

  //light "candles"
  for (ringSize = 0;ringSize < SIZEOFARRAY(ringsSize); ++ringSize) {
    totalLed -= ringsSize[ringSize]; 
    for(led = 0; led < ringsSize[ringSize] / (ringSize + 1); led++) {
      strip.setPixelColor(totalLed + random(ringsSize[ringSize]), strip.Color(255, 255, 255));
      if (!_blink) { 
        strip.show();
        delay(50);
      }
    }
    if (_blink) strip.show();
  }
}
```

Blink now really blink, and the random '3', is now more logical [Replaced by 'ringSize' which will be bigger the more ring you have]
Simulation updated too : https://wokwi.com/projects/348700019704988244

**Review by designer2k2 — CHANGES_REQUESTED** [review]
This is realy optimized, from 4180 Bytes down to 3998 Bytes, that gives more room for others.
My tree here is now running this code :-)

But i have some needed changes:

- [x] Rename back to xmas_tree.ino so that it directly compiles (git mv xmas-tree_optimized.ino xmas-tree.ino)
- [x] Restore the original header, feel free to add yourself 
- [x] Apply the Arduino IDE formatting: Edit > Auto Format, or  [STRG]+[T] or [CMD] + [T]

**Comment by kaldoran** [comment]
Should now be ok.
Sorry for the credit was not supposed to remove them.

In the mean time : 
https://wokwi.com/projects/348700019704988244

I did add a sparkling effect, and the blinking effect on both normal and random tree.
But memory goes to 6394 Bytes

**Comment by designer2k2** [comment]
thanks for the changes! Looks good to merge for me.

As long as it fits on the ATtiny85 (Digispark) every pattern/feature can be added.  Go ahead and add your sparkling/blinking

EDIT: Let me know if you want to make further changes here or i should merge

**Pull request merged**
